server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
data:
  database:
    driver: mysql
    source: root:dangerous@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    db: 1
    cache_expiration: 1800s
    read_timeout: 0.2s
    write_timeout: 0.2s
  path:
    path: "/data"
jwt:
  secret: "hello"