version: '3.4'

services:
  bugu-bugu-service:
    image: hominsu/bugu-bugu-service:latest
    container_name: bugu-bugu-service
    restart: always
    depends_on:
      bugu-obfusion-service:
        condition: service_started
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - type: bind
        source: "../../app/bugu/service/configs"
        target: "/data/conf"
        bind:
          create_host_path: true
      - type: bind
        source: "./data/file"
        target: "/data/file"
        bind:
          create_host_path: true
    ports:
      - mode: ingress
        target: 8000
        published: 8000
        protocol: tcp
    networks:
      net:
        aliases:
          - bugu-bugu-service

  bugu-obfusion-service:
    image: hominsu/bugu-obfusion-service:latest
    container_name: bugu-obfusion-service
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - type: bind
        source: "../../app/obfusion/service/configs"
        target: "/data/conf"
        bind:
          create_host_path: true
    ports:
      - mode: ingress
        target: 9000
        published: 9000
        protocol: tcp
    networks:
      net:
        aliases:
          - bugu-obfusion-service

  bugu-detect-service:
    image: hominsu/bugu-detect-service:latest
    container_name: bugu-detect-service
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - type: bind
        source: "../../app/detect/service/configs"
        target: "/data/conf"
        bind:
          create_host_path: true
    ports:
      - mode: ingress
        target: 9000
        published: 9000
        protocol: tcp
    networks:
      net:
        aliases:
          - bugu-detect-service

  bugu-packer-service:
    image: hominsu/bugu-packer-service:latest
    container_name: bugu-packer-service
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - type: bind
        source: "../../app/packer/service/configs"
        target: "/data/conf"
        bind:
          create_host_path: true
    ports:
      - mode: ingress
        target: 9000
        published: 9000
        protocol: tcp
    networks:
      net:
        aliases:
          - bugu-packer-service

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/24
