version: '3.4'

services:
  bugu-bugu-service:
    image: hominsu/bugu-bugu-service:latest
    container_name: bugu-bugu-service
    restart: always
    depends_on:
      - bugu-obfusion-service
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "../../app/bugu/service/configs:/data/conf"
      - "./data/file:/data/file"
    ports:
      - "8000:8000"
    networks:
      net:
        aliases:
          - bugu-bugu-service

  bugu-obfusion-service:
    image: hominsu/bugu-obfusion-service:latest
    container_name: bugu-obfusion-service
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "../../app/obfusion/service/configs:/data/conf"
    ports:
      - "9000:9000"
    networks:
      net:
        aliases:
          - bugu-obfusion-service

  bugu-detect-service:
    image: hominsu/bugu-detect-service:latest
    container_name: bugu-detect-service
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "../../app/detect/service/configs:/data/conf"
    ports:
      - "9000:9000"
    networks:
      net:
        aliases:
          - bugu-detect-service

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/24
